---
spring:
  config.activate.on-profile: default
  sql.init:
    mode: never
    schema-locations: classpath:schema-sqlite.sql
  datasource:
    url: "jdbc:sqlite:db.sqlite"
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      max-lifetime: 0
